### PR TITLE
Update dependencies (SHOOP-1954)

### PR DESCRIPTION
**Pull request by akx**

### CODE REVIEW

**Comment by akx** [comment]
Welp, I have no idea what's gotten Jenkins' panties in a bunch, but the PR works fine on Travis?

**Comment by suutari-ai** [comment]
I have this already in-progress too...

Planned to update most of the deps to ">=" form.

**Comment by akx** [comment]
It wasn't in progress in JIRA when I started doing this, so I figured it wasn't in progress with you.

**Comment by akx** [comment]
Anyway, the work's already been done here. :)

**Comment by suutari-ai** [comment]
Yep, here too: https://github.com/suutari-ai/shoop/commits/81ffca8bbe8a80956ad312601123791e3318606d

We should combine the best parts. :)

**Comment by akx** [comment]
@suutari-ai Feel free to cherry-pick what's necessary, of course.

**Comment by suutari-ai** [comment]
@akx Yes, will do just that. Thanks!

Closing this for now... will get back to this soon with another PR. (Just don't delete the branch just yet, so I can cherry pick from there.)

**Pull request closed without merging**
