### PR TITLE
Update model and form verbose names (SHOOP-2002)

### PR DESCRIPTION
**Pull request by suutari-ai**

### CODE REVIEW

**Comment by suutari-ai** [comment]
This PR is created based on #304 and addresses my comments over there.

**Comment by suutari-ai** [comment]
No.. wait.. this will need migrations... as @akx pointed in #304... why didn't our check catch that?

**Comment by suutari-ai** [comment]
Added migrations.

Our check didn't catch missing migrations, because it didn't exists when #304 was created. :)

**Comment by suutari-ai** [comment]
retest this please

**Comment by tulimaki** [comment]
Good. And the migrations test works after all.

**Pull request merged**
