### PR TITLE
Core: Fix migration 0013_address_changes (SHOOP-2003)

### PR DESCRIPTION
**Pull request by tulimaki**
* Do RenameModel first, which handles all foreign key changes to database.
* FakeAlterField applies only state forwards.

### CODE REVIEW

**Comment by akx** [comment]
What happens if you try to rewind this migration? Considering FakeAlterField still does _something_ when moving backwards.

Also, it would be nice if the commit message explained what is being fixed, and why.

**Comment by tulimaki** [comment]
Migrating backwards is not supported for this migration since copy order addresses goes only forward. And I think we want it to be that way.

**Comment by akx** [comment]
Fair enough.

Still, the point about the commit message not explaining what is fixed and why a fix is needed stands.

**Comment by tulimaki** [comment]
Updated commit message.

**Comment by akx** [comment]
Hey, actually: can you add a test that attempts to run `makemigrations` (in some dry-run mode?) that ensures

* that makemigrations does not crash
* that makemigrations does not attempt to create new migrations (as they should have been done by the dev in the PR)

**Comment by suutari-ai** [comment]
Is this tested with at least MySQL and SQLite now?

**Comment by tulimaki** [comment]
Yes tested with both sqlite and mysql. Also added test that makemigration does not provide any new migrations and it goes through successfully.

**Pull request merged**
