### PR TITLE
Add missing dependency django-registration-redux

### PR DESCRIPTION
**Pull request by jaywink**

### CODE REVIEW

**Comment by akx** [comment]
This is already mentioned in the `extras` for `'shoop.front.apps.registration'` (it's not a strict requirement to use the Shoop Core, nor the default frontend either if you don't need registration).

**Comment by suutari-ai** [comment]
That's actually very odd that we define only that dep as optional. We probably should (1) move all the deps to the same list or (2) move all the optional ones to extras or (3) create separate Python packages for Shoop Core, Shoop Front, Shoop Admin, etc.

**Comment by akx** [comment]
@suutari-ai -- it's odd only because it's the first one to have had that sort of dependency. `shoop.api` (once it lands) will be another.

**Comment by jaywink** [comment]
I think #28 handles this so closing :)

**Pull request closed without merging**
