### PR TITLE
Media browser bugfixes

### PR DESCRIPTION
**Pull request by akx**
Thanks to @tselkala 's excellent sleuthing, a couple bugs were uncovered.

And then ruthlessly squished.

Refs SHOOP-503/SHOOP-1335/SHOOP-1336/SHOOP-1337/SHOOP-1340

### CODE REVIEW

**Comment by Pikkupomo** [comment]
@akx rebase please

**Comment by akx** [comment]
Rebased, @Pikkupomo, though it was showing a green light to me as it is.

**Comment by akx** [comment]
Rebased on fa1c0e89b9c5f1db78153e19620b13923c8a1e3c after #107 was merged.

**Comment by tulimaki** [comment]
:+1:

**Pull request merged**
