### PR TITLE
Add link to admin panel in frontend

### PR DESCRIPTION
**Pull request by Pikkupomo**
Refs SHOOP-1053

### CODE REVIEW

**Comment by juhakujala** [comment]
:+1:

**Comment by akx** [comment]
This will break if the `shoop.admin` app isn't installed.

**Comment by suutari-ai** [comment]
Yeah, shoop.admin should add such link through UI extension mechanisms which are not yet implemented (nor designed). Until that, we can just assume that shoop.admin is always installed.

**Comment by akx** [comment]
@suutari-ai: for now we should just follow what the other conditionally enabled links do, i.e. wrap the link in

```jinja
{% if shoop.urls.has_url("shoop_admin:dashboard") %}
```

**Comment by suutari-ai** [comment]
That's fine too, but not required IMHO. The ifs are going away anyway.

**Pull request merged**
