### PR TITLE
Add `next` context variable in registration process

### PR DESCRIPTION
**Pull request by chessbr**
The `next` context variable contains an URL to redirect the user after a successful registration. It is optional and may allow redirects to certain pages after the registration.

### CODE REVIEW

**Comment by suutari-ai** [comment]
Very nice improvement. Thanks @chessbr!

Can you remove the merge commit from this PR? (Tell me if you don't know how. I would gladly help with it.)

**Comment by chessbr** [comment]
hmmm.. then I'll need your help this time, please :)

**Comment by suutari-ai** [comment]
OK. You can remove the unneeded merge commit by using git reset and then pushing the new tip of your branch. First, do the following on the branch which has your change (master?):
```sh
git reset --hard b9143b7
```
but be careful, since it will remove all commits on that branch that you have made on top of the b9143b7 commit. Then force-push your branch to Github with:
```sh
git push -f
```
That'll remove the merge commit from the server too and the PR should get updated automatically.

**Comment by suutari-ai** [comment]
The theme author @juhakujala noted that there is another registration link in shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja (line 88). Maybe you should add the "next" attribute there too?

**Comment by chessbr** [comment]
Ok @suutari-ai , I will change it too.

**Comment by tulimaki** [comment]
Thanks!

**Pull request merged**
