### PR TITLE
Admin: Show service choice name in service provider admin

### PR DESCRIPTION
**Pull request by shawnadelic**
Show service choice name in service provider admin list view.

### CODE REVIEW

**Comment by suutari-ai** [comment]
Thanks, Shawn!

**Comment by suutari-ai** [comment]
@shawnadelic: Just found out that I missed a bug in this. If the shipping/payment method does not have a service provider, this will raise an exception. Can you fix this?

**Comment by shawnadelic** [comment]
Yes, will do that

**Comment by shawnadelic** [comment]
Here is what I came up with: https://github.com/shoopio/shoop/pull/452

**Pull request merged**
