### PR TITLE
Do not forcibly update POT-Creation-Date with makemessages (SHOOP-1932)

### PR DESCRIPTION
**Pull request by suutari-ai**
Doing "shoop_makemessages" in the shoop directory updates all the
translation base files, but it unnecessarily updates also the
POT-Creation-Date header which causes all PO files to change even if
there is no change to messages.  This makes it hard to periodically
update the message files (with clean commits).

Update the Shoop's "makemessages" command to support skipping
POT-Creation-Date updating of PO files which don't have any changes to
messages and make "shoop_makemessages" to toggle that option on by
default.

### CODE REVIEW

**Comment by suutari-ai** [comment]
Oh wait.. a bug..

**Comment by suutari-ai** [comment]
doh.. another bug..

**Comment by suutari-ai** [comment]
Ah, the second one was actually older bug. makemessages didn't work with Python2: added another commit to fix that one too.

**Comment by tulimaki** [comment]
:lollipop:

**Pull request merged**
