### PR TITLE
Initial REST API implementation

### PR DESCRIPTION
**Pull request by akx**

### CODE REVIEW

**Comment by akx** [comment]
Aw, shucks. I didn't know you can't put pip requirement specs in `extras_require`... this'll have to wait for resolution of https://github.com/edoburu/django-parler-rest/issues/5 :)

**Comment by suutari-ai** [comment]
What should we do about this? Should we vendor django-parler-rest for now and replace it with a proper requirement later?

**Comment by akx** [comment]
Rebased and added vendored `django-parler-rest` pending https://github.com/edoburu/django-parler-rest/pulls/6

**Comment by suutari-ai** [comment]
Can you update VENDOR-LICENSES.md too?

**Comment by akx** [comment]
Certainly, juuust a moment.

**Comment by akx** [comment]
Done, @suutari-ai.

**Comment by suutari-ai** [comment]
Great stuff! :sunglasses:

**Pull request merged**
